### ISSUE TITLE
Action point turns into a black hole when under the grid

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2_editor#23]
![Screenshot from 2020-03-23 15-56-59](https://user-images.githubusercontent.com/1199396/77330109-27f4f480-6d1f-11ea-955f-68721a445efa.png)
![Screenshot from 2020-03-23 15-57-13](https://user-images.githubusercontent.com/1199396/77330111-29262180-6d1f-11ea-9802-f3406af427ad.png)
![Screenshot from 2020-03-23 15-57-42](https://user-images.githubusercontent.com/1199396/77330112-29262180-6d1f-11ea-898f-161b2032575b.png)

**Comment by xBambusekD** [comment]
This is caused by combination of directional light and black background in the editor. Directional light (white circle) casts light to the scene and the "black hole" is just an action point in shadow.
![Screenshot (36)](https://user-images.githubusercontent.com/26470087/77426815-8e3c4e80-6dd5-11ea-8328-4ae07f8f447d.png)

Solved by adding some ambient light to the scene:
![Screenshot (37)](https://user-images.githubusercontent.com/26470087/77427842-6352fa00-6dd7-11ea-8c58-3e43c1a48b38.png)
